package dev.orestegabo.sequohub.core.localization

import androidx.compose.runtime.staticCompositionLocalOf
import dev.orestegabo.sequohub.feature.settings.AppLanguage

data class SequoStrings(
    val navScan: String,
    val navActions: String,
    val navHub: String,
    val navAudit: String,
    val navSettings: String,
    val synced: String,
    val pending: String,
    val blocked: String,
    val occupied: String,
    val feesDue: String,
    val sync: String,
    val clear: String,
    val emptyLocker: String,
    val today: String,
    val yesterday: String,
    val pointDeRelai: String,
    val hubDashboard: String,
    val lockerSearchPlaceholder: String,
    val lockerGrid: String,
    val lockerGridHint: String,
    val blockedBySequo: String,
    val blockedHubNotice: String,
    val packageStored: String,
    val maintenance: String,
    val needsAttention: String,
    val attentionHint: String,
    val noLockerNeedsAttention: String,
    val locker: String,
    val packageAge: String,
    val reference: String,
    val nextAction: String,
    val custodyTimeline: String,
    val reportProblem: String,
    val close: String,
    val underMaintenance: String,
    val collectFeeOpenLocker: String,
    val intake: String,
    val scanPackage: String,
    val scanSubtitle: String,
    val fastPath: String,
    val manualFallback: String,
    val packageIdOrQrCode: String,
    val resolve: String,
    val condition: String,
    val scanPackageQr: String,
    val scanCameraHint: String,
    val startCameraScan: String,
    val bestFreeLocker: String,
    val assign: String,
    val sealedOk: String,
    val damaged: String,
    val handover: String,
    val handoverSubtitle: String,
    val idRequired: String,
    val pickup: String,
    val returnPackage: String,
    val customerPickup: String,
    val customerReturn: String,
    val pickupCode: String,
    val returnCode: String,
    val validate: String,
    val extraStorageFee: String,
    val collectBeforeRelease: String,
    val pickupReady: String,
    val feeDue: String,
    val freeWindow: String,
    val endedTwoDaysAgo: String,
    val storageFee: String,
    val source: String,
    val backendStorageRules: String,
    val returnDropOff: String,
    val returnWindowHint: String,
    val idCheck: String,
    val requiredBeforeIntake: String,
    val refundDecision: String,
    val sequoFinalValidationOnly: String,
    val receiveReturn: String,
    val audit: String,
    val activity: String,
    val activitySubtitle: String,
    val newLabel: String,
    val inbox: String,
    val notificationInbox: String,
    val inboxHint: String,
    val unread: String,
    val refreshInbox: String,
    val markRead: String,
    val archive: String,
    val restore: String,
    val settings: String,
    val hubSettings: String,
    val settingsSubtitle: String,
    val local: String,
    val appearance: String,
    val theme: String,
    val systemTheme: String,
    val lightTheme: String,
    val darkTheme: String,
    val largeLockerLabels: String,
    val largeLockerLabelsHint: String,
    val language: String,
    val displayLanguage: String,
    val counterWorkflow: String,
    val quickScanOnOpen: String,
    val quickScanOnOpenHint: String,
    val soundFeedback: String,
    val soundFeedbackHint: String,
    val operationalAlerts: String,
    val operationalAlertsHint: String,
    val on: String,
    val lockerControls: String,
    val temporarilyCloseLocker: String,
    val temporarilyCloseLockerHint: String,
    val openingHours: String,
    val notifications: String,
    val pushAlerts: String,
    val pushAlertsHint: String,
    val notificationChannels: String,
    val notificationChannelsHint: String,
    val stopAlerts: String,
    val stopAlertsHint: String,
    val supportPrivacy: String,
    val dataPrivacy: String,
    val dataPrivacyHint: String,
    val helpGuide: String,
    val helpGuideHint: String,
    val account: String,
    val logout: String,
    val logoutHint: String,
    val deleteAccount: String,
    val deleteAccountHint: String,
    val cancel: String,
    val requestDeletion: String,
    val logoutQuestion: String,
    val logoutDialogText: String,
    val deleteAccountQuestion: String,
    val deleteDialogText: String,
    val operatorProfilePermissions: String,
    val closeLocker: String,
    val closeLockerSubtitle: String,
    val selectLocker: String,
    val closureDetails: String,
    val reason: String,
    val expectedAvailableAgain: String,
    val closeLockerTemporarily: (String) -> String,
    val hubTimetable: String,
    val openingHoursSubtitle: String,
    val closedForDay: String,
    val closedForDayHint: String,
    val closeEarlierToday: String,
    val usualWeek: String,
    val saveTimetable: String,
    val open: String,
    val closedToday: String,
    val weekdays: String,
    val mon: String,
    val tue: String,
    val wed: String,
    val thu: String,
    val fri: String,
    val sat: String,
    val sun: String,
)

val LocalSequoStrings = staticCompositionLocalOf { englishStrings }

fun stringsFor(language: AppLanguage): SequoStrings =
    when (language) {
        AppLanguage.English -> englishStrings
        AppLanguage.French -> frenchStrings
        AppLanguage.EweMina -> eweMinaStrings
    }

private val englishStrings = SequoStrings(
    navScan = "Scan",
    navActions = "Actions",
    navHub = "Hub",
    navAudit = "History",
    navSettings = "Settings",
    synced = "Synced",
    pending = "pending",
    blocked = "Blocked",
    occupied = "Occupied",
    feesDue = "Fees due",
    sync = "Sync",
    clear = "clear",
    emptyLocker = "Empty",
    today = "today",
    yesterday = "Yesterday",
    pointDeRelai = "Relay point",
    hubDashboard = "Hub dashboard",
    lockerSearchPlaceholder = "Search locker, e.g. A04",
    lockerGrid = "Locker grid",
    lockerGridHint = "Tap a box to inspect package age and status.",
    blockedBySequo = "Blocked by Sequo",
    blockedHubNotice = "Sequo has temporarily paused new drop-offs at this hub. Customers may still collect packages already stored here, but no new packages can be accepted until the hub is reactivated.",
    packageStored = "Package stored",
    maintenance = "Maintenance",
    needsAttention = "Needs attention",
    attentionHint = "Maintenance, fee due, and local actions waiting to sync.",
    noLockerNeedsAttention = "No locker needs attention right now.",
    locker = "Locker",
    packageAge = "Package age",
    reference = "Reference",
    nextAction = "Next action",
    custodyTimeline = "Custody timeline",
    reportProblem = "Report problem",
    close = "Close",
    underMaintenance = "Under Maintenance",
    collectFeeOpenLocker = "Collect Fee & Open Locker",
    intake = "Intake",
    scanPackage = "Scan package",
    scanSubtitle = "Incoming parcel or Plan B delivery",
    fastPath = "Fast path",
    manualFallback = "Manual fallback",
    packageIdOrQrCode = "Package ID or QR code",
    resolve = "Resolve",
    condition = "Condition",
    scanPackageQr = "Scan package QR",
    scanCameraHint = "Open the camera only when staff starts intake.",
    startCameraScan = "Start camera scan",
    bestFreeLocker = "Best free locker",
    assign = "Assign",
    sealedOk = "Sealed OK",
    damaged = "Damaged",
    handover = "Handover",
    handoverSubtitle = "Pickup and return workflows",
    idRequired = "ID required",
    pickup = "Pickup",
    returnPackage = "Return",
    customerPickup = "Customer pickup",
    customerReturn = "Customer return",
    pickupCode = "Pickup code",
    returnCode = "Return code",
    validate = "Validate",
    extraStorageFee = "Extra storage fee",
    collectBeforeRelease = "Collect before package release.",
    pickupReady = "Pickup ready",
    feeDue = "Fee due",
    freeWindow = "Free window",
    endedTwoDaysAgo = "Ended 2 days ago",
    storageFee = "Storage fee",
    source = "Source",
    backendStorageRules = "Backend storage rules",
    returnDropOff = "Return drop-off",
    returnWindowHint = "Validate within the 72-hour return window.",
    idCheck = "ID check",
    requiredBeforeIntake = "Required before intake",
    refundDecision = "Refund decision",
    sequoFinalValidationOnly = "Sequo final validation only",
    receiveReturn = "Receive Return",
    audit = "History",
    activity = "History",
    activitySubtitle = "Scans, pickups, returns, and hub notifications",
    newLabel = "new",
    inbox = "Inbox",
    notificationInbox = "Notification inbox",
    inboxHint = "Push and in-app alerts for this SequoHub device.",
    unread = "unread",
    refreshInbox = "Refresh inbox",
    markRead = "Mark read",
    archive = "Archive",
    restore = "Restore",
    settings = "Settings",
    hubSettings = "Hub settings",
    settingsSubtitle = "Account, language, appearance, and counter flow",
    local = "Local",
    appearance = "Appearance",
    theme = "Theme",
    systemTheme = "System",
    lightTheme = "Light",
    darkTheme = "Dark",
    largeLockerLabels = "Large locker labels",
    largeLockerLabelsHint = "Bigger A01-E05 labels for busy counters.",
    language = "Language",
    displayLanguage = "Display language",
    counterWorkflow = "Counter workflow",
    quickScanOnOpen = "Quick scan on open",
    quickScanOnOpenHint = "Start from the fastest scan-first intake flow.",
    soundFeedback = "Sound feedback",
    soundFeedbackHint = "Play soft confirmations after validation.",
    operationalAlerts = "Operational alerts",
    operationalAlertsHint = "Fee reminders, maintenance, and collection alerts.",
    on = "On",
    lockerControls = "Locker controls",
    temporarilyCloseLocker = "Temporarily close a locker",
    temporarilyCloseLockerHint = "Mark a broken or unusable locker as unavailable.",
    openingHours = "Opening hours",
    notifications = "Notifications",
    pushAlerts = "Push alerts",
    pushAlertsHint = "Register this phone for hub pickup, return, and collection alerts.",
    notificationChannels = "Notification channels",
    notificationChannelsHint = "Push, in-app, SMS, and quiet hours for hub events.",
    stopAlerts = "Stop alerts on this phone",
    stopAlertsHint = "Revoke this device when it is no longer used at the counter.",
    supportPrivacy = "Support and privacy",
    dataPrivacy = "Data and privacy",
    dataPrivacyHint = "Identity checks, audit records, and device tokens.",
    helpGuide = "Help and counter guide",
    helpGuideHint = "Pickup, return, and damaged parcel instructions.",
    account = "Account",
    logout = "Logout",
    logoutHint = "End this staff session on the device.",
    deleteAccount = "Delete account",
    deleteAccountHint = "Request account removal for this staff profile.",
    cancel = "Cancel",
    requestDeletion = "Request deletion",
    logoutQuestion = "Logout?",
    logoutDialogText = "This will end the staff session on this device.",
    deleteAccountQuestion = "Delete account?",
    deleteDialogText = "This requests removal of the staff profile from SequoHub. Hub audit records may be retained for operations history.",
    operatorProfilePermissions = "Operator profile and permissions",
    closeLocker = "Close locker",
    closeLockerSubtitle = "Choose the locker and recovery note",
    selectLocker = "Select locker",
    closureDetails = "Closure details",
    reason = "Reason",
    expectedAvailableAgain = "Expected available again",
    closeLockerTemporarily = { id -> "Close $id temporarily" },
    hubTimetable = "Hub timetable",
    openingHoursSubtitle = "Keep pickup promises aligned with shop hours",
    closedForDay = "Closed for the day",
    closedForDayHint = "Use for holidays, stock count, or emergency closure.",
    closeEarlierToday = "Close earlier today",
    usualWeek = "Usual week",
    saveTimetable = "Save timetable",
    open = "Open",
    closedToday = "Closed today",
    weekdays = "Weekdays",
    mon = "Mon",
    tue = "Tue",
    wed = "Wed",
    thu = "Thu",
    fri = "Fri",
    sat = "Sat",
    sun = "Sun",
)

private val frenchStrings = englishStrings.copy(
    navScan = "Scanner",
    navActions = "Actions",
    navHub = "Hub",
    navAudit = "Historique",
    navSettings = "Parametres",
    synced = "Synchronise",
    pending = "en attente",
    blocked = "Bloque",
    occupied = "Occupes",
    feesDue = "Frais dus",
    sync = "Sync",
    clear = "ok",
    emptyLocker = "Vide",
    today = "aujourd'hui",
    yesterday = "Hier",
    pointDeRelai = "Point relais",
    hubDashboard = "Tableau du hub",
    lockerSearchPlaceholder = "Rechercher un casier, ex. A04",
    lockerGrid = "Grille des casiers",
    lockerGridHint = "Touchez un casier pour voir l'age et le statut du colis.",
    blockedBySequo = "Bloque par Sequo",
    blockedHubNotice = "Sequo a temporairement suspendu les nouveaux depots dans ce hub. Les clients peuvent encore retirer les colis deja stockes ici, mais aucun nouveau colis ne peut etre accepte avant la reactivation du hub.",
    packageStored = "Colis stocke",
    maintenance = "Maintenance",
    needsAttention = "A traiter",
    attentionHint = "Maintenance, frais dus et actions locales en attente de synchronisation.",
    noLockerNeedsAttention = "Aucun casier ne demande d'attention pour le moment.",
    locker = "Casier",
    packageAge = "Age du colis",
    reference = "Reference",
    nextAction = "Prochaine action",
    custodyTimeline = "Suivi du colis",
    reportProblem = "Signaler un probleme",
    close = "Fermer",
    underMaintenance = "En maintenance",
    collectFeeOpenLocker = "Encaisser et ouvrir",
    intake = "Reception",
    scanPackage = "Scanner le colis",
    scanSubtitle = "Colis entrant ou livraison Plan B",
    fastPath = "Rapide",
    manualFallback = "Saisie manuelle",
    packageIdOrQrCode = "ID colis ou code QR",
    resolve = "Verifier",
    condition = "Etat",
    scanPackageQr = "Scanner le QR du colis",
    scanCameraHint = "Ouvrir la camera uniquement au debut de la reception.",
    startCameraScan = "Lancer le scan",
    bestFreeLocker = "Meilleur casier libre",
    assign = "Attribuer",
    sealedOk = "Bien scelle",
    damaged = "Abime",
    handover = "Remise",
    handoverSubtitle = "Flux de retrait et de retour",
    idRequired = "ID requis",
    pickup = "Retrait",
    returnPackage = "Retour",
    customerPickup = "Retrait client",
    customerReturn = "Retour client",
    pickupCode = "Code de retrait",
    returnCode = "Code de retour",
    validate = "Valider",
    extraStorageFee = "Frais de garde",
    collectBeforeRelease = "A encaisser avant de remettre le colis.",
    pickupReady = "Retrait pret",
    feeDue = "Frais dus",
    freeWindow = "Delai gratuit",
    endedTwoDaysAgo = "Termine il y a 2 jours",
    storageFee = "Frais de stockage",
    source = "Source",
    backendStorageRules = "Regles de stockage backend",
    returnDropOff = "Depot retour",
    returnWindowHint = "Valider pendant la fenetre de retour de 72 heures.",
    idCheck = "Controle ID",
    requiredBeforeIntake = "Requis avant reception",
    refundDecision = "Decision de remboursement",
    sequoFinalValidationOnly = "Validation finale par Sequo uniquement",
    receiveReturn = "Recevoir le retour",
    audit = "Historique",
    activity = "Historique",
    activitySubtitle = "Scans, retraits, retours et notifications du hub",
    newLabel = "nouveau",
    inbox = "Boite",
    notificationInbox = "Notifications",
    inboxHint = "Alertes push et internes pour cet appareil SequoHub.",
    unread = "non lu",
    refreshInbox = "Actualiser",
    markRead = "Marquer lu",
    archive = "Archiver",
    restore = "Restaurer",
    settings = "Parametres",
    hubSettings = "Parametres du hub",
    settingsSubtitle = "Compte, langue, apparence et flux comptoir",
    local = "Local",
    appearance = "Apparence",
    theme = "Theme",
    systemTheme = "Systeme",
    lightTheme = "Clair",
    darkTheme = "Sombre",
    largeLockerLabels = "Grandes etiquettes",
    largeLockerLabelsHint = "Etiquettes A01-E05 plus lisibles aux comptoirs charges.",
    language = "Langue",
    displayLanguage = "Langue d'affichage",
    counterWorkflow = "Flux comptoir",
    quickScanOnOpen = "Scan rapide au demarrage",
    quickScanOnOpenHint = "Demarrer par le flux de reception le plus rapide.",
    soundFeedback = "Sons de confirmation",
    soundFeedbackHint = "Jouer une confirmation douce apres validation.",
    operationalAlerts = "Alertes operations",
    operationalAlertsHint = "Rappels de frais, maintenance et collectes.",
    on = "Actif",
    lockerControls = "Controle des casiers",
    temporarilyCloseLocker = "Fermer temporairement un casier",
    temporarilyCloseLockerHint = "Marquer un casier casse ou inutilisable comme indisponible.",
    openingHours = "Horaires",
    pushAlerts = "Alertes push",
    pushAlertsHint = "Enregistrer ce telephone pour les alertes retrait, retour et collecte.",
    notificationChannels = "Canaux de notification",
    notificationChannelsHint = "Push, app, SMS et heures calmes pour les evenements du hub.",
    stopAlerts = "Arreter les alertes sur ce telephone",
    stopAlertsHint = "Revoquer cet appareil quand il n'est plus utilise au comptoir.",
    supportPrivacy = "Support et confidentialite",
    dataPrivacy = "Donnees et confidentialite",
    dataPrivacyHint = "Controles d'identite, journaux d'audit et jetons appareil.",
    helpGuide = "Aide et guide comptoir",
    helpGuideHint = "Instructions retrait, retour et colis abime.",
    account = "Compte",
    logout = "Deconnexion",
    logoutHint = "Terminer cette session employe sur l'appareil.",
    deleteAccount = "Supprimer le compte",
    deleteAccountHint = "Demander la suppression de ce profil employe.",
    cancel = "Annuler",
    requestDeletion = "Demander la suppression",
    logoutQuestion = "Se deconnecter ?",
    logoutDialogText = "Cela terminera la session employe sur cet appareil.",
    deleteAccountQuestion = "Supprimer le compte ?",
    deleteDialogText = "Cela demande la suppression du profil employe dans SequoHub. Les journaux d'audit du hub peuvent etre conserves pour l'historique des operations.",
    operatorProfilePermissions = "Profil operateur et permissions",
    closeLocker = "Fermer le casier",
    closeLockerSubtitle = "Choisir le casier et la note de remise en service",
    selectLocker = "Choisir un casier",
    closureDetails = "Details de fermeture",
    reason = "Raison",
    expectedAvailableAgain = "Disponibilite prevue",
    closeLockerTemporarily = { id -> "Fermer $id temporairement" },
    hubTimetable = "Horaires du hub",
    openingHoursSubtitle = "Aligner les promesses de retrait avec les horaires du magasin",
    closedForDay = "Ferme pour la journee",
    closedForDayHint = "A utiliser pour ferie, inventaire ou fermeture d'urgence.",
    closeEarlierToday = "Fermer plus tot aujourd'hui",
    usualWeek = "Semaine habituelle",
    saveTimetable = "Enregistrer les horaires",
    open = "Ouvre",
    closedToday = "Ferme aujourd'hui",
    weekdays = "Semaine",
)

// First-pass Ewe/Mina copy for field testing. Local operations should review before release.
private val eweMinaStrings = englishStrings.copy(
    navScan = "Scan",
    navActions = "Dɔwɔwɔ",
    navHub = "Hub",
    navAudit = "History",
    navSettings = "Ðoɖowɔwɔ",
    synced = "Ede asi",
    pending = "le mɔ dzi",
    blocked = "Woɖe asi le eŋu",
    occupied = "Eyɔ fũu",
    feesDue = "Fe le eme",
    sync = "Sync",
    clear = "ewo",
    emptyLocker = "Mele eme o",
    today = "egbe",
    yesterday = "etsɔ",
    pointDeRelai = "Relay point",
    hubDashboard = "Hub kpɔɖeŋu",
    lockerSearchPlaceholder = "Di casier, abe A04",
    lockerGrid = "Casierwo ƒe ta",
    lockerGridHint = "Zi casier dzi be nàkpɔ colis ƒe ɣeyiɣi kple nɔnɔme.",
    blockedBySequo = "Sequo xe mɔ",
    blockedHubNotice = "Sequo ɖe asi le colis yeye xɔxɔ me le hub sia. Ameawo ate ŋu axɔ colis siwo le afisia xoxo, gake colis yeye aɖeke mate ŋu axɔ o va se ɖe hub la agbugbɔ wɔ dɔ.",
    packageStored = "Colis le eme",
    maintenance = "Gbugbɔwɔwɔ",
    needsAttention = "Ele be woakpɔe",
    attentionHint = "Gbugbɔwɔwɔ, fe siwo le eme, kple dɔ siwo le mɔ dzi.",
    noLockerNeedsAttention = "Casier aɖeke mehia kpɔkpɔ fifia o.",
    locker = "Casier",
    packageAge = "Colis ƒe ɣeyiɣi",
    reference = "Dzesi",
    nextAction = "Dɔ si ava",
    custodyTimeline = "Colis ƒe mɔ",
    reportProblem = "Gblɔ kuxi",
    close = "Tutu",
    underMaintenance = "Le gbugbɔwɔwɔ me",
    collectFeeOpenLocker = "Xɔ fe eye na casier woʋu",
    intake = "Xɔxɔ",
    scanPackage = "Scan colis",
    scanSubtitle = "Colis yeye alo Plan B",
    fastPath = "Mɔ kabakaba",
    manualFallback = "Ŋlɔ code",
    packageIdOrQrCode = "Colis ID alo QR code",
    resolve = "Kpɔ ŋu",
    condition = "Nɔnɔme",
    scanPackageQr = "Scan colis QR",
    scanCameraHint = "ʋu camera ne dɔwɔla dze xɔxɔ gɔme.",
    startCameraScan = "Dze scan gɔme",
    bestFreeLocker = "Casier dzadzɛ nyuie",
    assign = "Na eƒe teƒe",
    sealedOk = "Wotu nyuie",
    damaged = "Egbã",
    handover = "Asi me nana",
    handoverSubtitle = "Colis xɔxɔ kple retour",
    idRequired = "ID hia",
    pickup = "Xɔ colis",
    returnPackage = "Retour",
    customerPickup = "Client xɔ colis",
    customerReturn = "Client retour",
    pickupCode = "Code xɔxɔ",
    returnCode = "Code retour",
    validate = "Da asi dzi",
    extraStorageFee = "Fe bubu",
    collectBeforeRelease = "Xɔ fe hafi nàna colis.",
    pickupReady = "Colis le mɔ",
    feeDue = "Fe le eme",
    freeWindow = "Ɣeyiɣi dzadzɛ",
    endedTwoDaysAgo = "Ewu ŋkeke 2 va yi",
    storageFee = "Fe nɔƒe",
    source = "Teƒe tso",
    backendStorageRules = "Backend ƒe sewo",
    returnDropOff = "Retour gblẽɖi",
    returnWindowHint = "Kpɔ eŋu le ga 72 me.",
    idCheck = "ID kpɔkpɔ",
    requiredBeforeIntake = "Ele be woakpɔe hafi xɔxɔ",
    refundDecision = "Ga gbɔgbɔ ƒe nyawo",
    sequoFinalValidationOnly = "Sequo koe ana mɔ mamlɛ",
    receiveReturn = "Xɔ retour",
    audit = "History",
    activity = "History",
    activitySubtitle = "Scanwo, colis xɔxɔ, retourwo kple hub ƒe nyawo",
    newLabel = "yeye",
    inbox = "Nyawo",
    notificationInbox = "Nyawo",
    inboxHint = "Nyawo na SequoHub telefon sia.",
    unread = "womexlẽ o",
    refreshInbox = "Gbugbɔ kpɔ",
    markRead = "De asi be woxlẽ",
    archive = "Dzra ɖo",
    restore = "Gbugbɔ ekɔ",
    settings = "Ðoɖowɔwɔ",
    hubSettings = "Hub ɖoɖo",
    settingsSubtitle = "Account, gbe, ŋutinu kple comptoir dɔ",
    local = "Afisia",
    appearance = "Nɔnɔme",
    theme = "Theme",
    systemTheme = "System",
    lightTheme = "Kekeli",
    darkTheme = "Yibɔ",
    largeLockerLabels = "Casier ŋkɔ gãwo",
    largeLockerLabelsHint = "A01-E05 ŋkɔwo le gã na comptoir si me dɔ le.",
    language = "Gbe",
    displayLanguage = "Gbe si app la awɔ",
    counterWorkflow = "Comptoir dɔ",
    quickScanOnOpen = "Scan kabakaba le gɔme",
    quickScanOnOpenHint = "Dze egɔme kple xɔxɔ mɔ kabakaba.",
    soundFeedback = "Ɖiɖi ŋuɖoɖo",
    soundFeedbackHint = "Na gbe bɔbɔe ne validation wu enu.",
    operationalAlerts = "Dɔ nyawo",
    operationalAlertsHint = "Fe, gbugbɔwɔwɔ, kple collection nyawo.",
    on = "Le dɔ wɔm",
    lockerControls = "Casierwo kpɔkpɔ",
    temporarilyCloseLocker = "Tutu casier ɣeyiɣi aɖe",
    temporarilyCloseLockerHint = "De asi le casier gbã alo si mate ŋu awɔ dɔ o.",
    openingHours = "Ɣeyiɣi ʋuʋu",
    pushAlerts = "Push nyawo",
    pushAlertsHint = "De telefon sia ŋkɔ na retrait, retour kple collection nyawo.",
    notificationChannels = "Nya mɔwo",
    notificationChannelsHint = "Push, app, SMS kple ɣeyiɣi faɖi.",
    stopAlerts = "Tutu nyawo le telefon sia",
    stopAlertsHint = "Ɖe telefon sia le dɔ me ne womegazãa le comptoir o.",
    supportPrivacy = "Kpekpeɖeŋu kple private",
    dataPrivacy = "Data kple private",
    dataPrivacyHint = "ID kpɔkpɔ, audit agbalẽwo kple telefon token.",
    helpGuide = "Kpekpeɖeŋu kple guide",
    helpGuideHint = "Retrait, retour kple colis gbã ƒe ɖoɖo.",
    account = "Account",
    logout = "Do go",
    logoutHint = "Wu dɔwɔla ƒe session le telefon sia dzi.",
    deleteAccount = "Tututu account",
    deleteAccountHint = "Bia be woaɖe dɔwɔla account sia ɖa.",
    cancel = "Gbe ɖi",
    requestDeletion = "Bia tututu",
    logoutQuestion = "Do go?",
    logoutDialogText = "Esia awu dɔwɔla ƒe session le telefon sia dzi.",
    deleteAccountQuestion = "Tutu account?",
    deleteDialogText = "Esia abia be woaɖe dɔwɔla ƒe profile le SequoHub. Hub audit agbalẽwo ate ŋu anɔ anyi na dɔwo ƒe ŋutinya.",
    operatorProfilePermissions = "Dɔwɔla profile kple mɔɖeɖe",
    closeLocker = "Tutu casier",
    closeLockerSubtitle = "Tia casier kple note na gbugbɔwɔwɔ",
    selectLocker = "Tia casier",
    closureDetails = "Tututu ƒe nya",
    reason = "Taɖodzinu",
    expectedAvailableAgain = "Ɣeyiɣi si ava dzadzɛ",
    closeLockerTemporarily = { id -> "Tutu $id ɣeyiɣi aɖe" },
    hubTimetable = "Hub ƒe ɣeyiɣi",
    openingHoursSubtitle = "Na retrait ŋugbedodo sɔ kple boutique ƒe ɣeyiɣi",
    closedForDay = "Woɖe asi egbe",
    closedForDayHint = "Zãe na fête, inventory alo kuxi dzi tututu.",
    closeEarlierToday = "Tutu kaba egbe",
    usualWeek = "Kwasiɖa sia kwasiɖa",
    saveTimetable = "Dzra ɣeyiɣi ɖo",
    open = "ʋu",
    closedToday = "Woɖe asi egbe",
    weekdays = "Dɔŋkekewo",
)
